# Generated by Django 4.2 on 2023-06-15 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0002_requirement_skill_user_delete_commercial_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('RM', 'Ressource Manager'), ('RH', 'Human Ressource'), ('Com', 'Commercial')], max_length=5),
        ),
    ]
