# Generated by Django 4.2 on 2023-06-15 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultant',
            name='in_intercontrat',
            field=models.BooleanField(default=True),
        ),
    ]
