# Generated by Django 4.2.1 on 2023-06-21 09:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0004_consultant_in_intercontrat'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='date_creation',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
